### ISSUE TITLE
Getting error on fresh project

### ISSUE THREAD

**Issue by peec** [sanity-io/sanity-plugin-transifex#6]
Hi,

I was going to test out this plugin and transifex,

But it fails after installing the plugin on a fresh project (only got vision installed), using `sanity install sanity-plugin-transifex`. Using `npm install sanity-plugin-transifex` failed so used sanity install instead.

```
(base) ➜  pk-transifex-test sanity versions
@sanity/cli             2.15.0 (up to date)
@sanity/base            2.15.1 (up to date)
@sanity/components      2.14.0 (up to date)
@sanity/core            2.15.0 (up to date)
@sanity/default-layout  2.15.1 (up to date)
@sanity/default-login   2.15.0 (up to date)
@sanity/desk-tool       2.15.2 (up to date)
@sanity/vision          2.15.0 (up to date)
```

<img width="1175" alt="Skjermbilde 2021-08-23 kl  10 45 03" src="https://user-images.githubusercontent.com/131546/130418312-21c5c2be-c605-4771-9a1d-51bc3652707e.png">

Removing "transifex" from plugins resolves it. 

My sanity.json looks like this:

```
{
  "root": true,
  "project": {
    "name": "y"
  },
  "api": {
    "projectId": "x",
    "dataset": "production"
  },
  "plugins": [
    "@sanity/base",
    "@sanity/components",
    "@sanity/default-layout",
    "@sanity/default-login",
    "@sanity/desk-tool",
    "@sanity/vision",
    "transifex"
  ],
  "env": {
    "development": {
      "plugins": [
        "@sanity/vision"
      ]
    }
  },
  "parts": [
    {
      "name": "part:@sanity/base/schema",
      "path": "./schemas/schema"
    }
  ]
}

```

**Comment by cngonzalez** [comment]
Hi there! Unfortunately, `sanity install` won't work for this particular plugin, as it's relatively standalone and outside of the Sanity parts system.

May I ask how `npm install` failed? It's the recommended install method.
